### ISSUE TITLE
Quote class not working

### ISSUE THREAD

**Issue by alberto33** [oscar0812/pyfinviz#22]
I think this is happening because the pyfinviz changed their layout again.

The Quote example:
```
    quote = Quote(ticker="AMZN")

    # available variables:
    print(quote.exists)  # check if fetch was successful (STOCK may not exist)
    print(quote.ticker)  # AMZN
```

Is throwing this error:
```
Traceback (most recent call last):
  File "C:\Users\alber\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\222.4459.20\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Users\alber\AppData\Local\JetBrains\Toolbox\apps\PyCharm-C\ch-0\222.4459.20\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\alber\PycharmProjects\StrategyScanner\strategyscanner\pyfinviz_tester.py", line 26, in <module>
    test2()
  File "C:\Users\alber\PycharmProjects\StrategyScanner\strategyscanner\pyfinviz_tester.py", line 14, in test2
    print(quote.ticker)  # AMZN
AttributeError: 'Quote' object has no attribute 'ticker'

```

I don't yet understand the code well enough to send a PR

**Comment by oscar0812** [comment]
Oh my, finviz is having constant updates this week! I will look into it asap. Thank you for the ticket.

**Comment by alberto33** [comment]
Yes, confirmed! Thank you.

**Comment by oscar0812** [comment]
Great! Please keep opening tickets when something breaks. Closing this one now.
