### ISSUE TITLE
`Quote.__get_outer_ratings_df__` fails when `o_tds_text` is an empty list.

### ISSUE THREAD

**Issue by ivnle** [oscar0812/pyfinviz#8]
Adding the check below resolves the issue.

```python
    @staticmethod
    def __get_outer_ratings_df__(soup):
        outer_ratings_table = soup.find('table', class_='fullview-ratings-outer')
        # might not have outer ratings
        if outer_ratings_table is None:
            return None

        outer_ratings_trs = outer_ratings_table.find_all('tr', recursive=False)

        outer_ratings_info = []
        tags__ = ['Date', 'Status', 'Outer', 'Rating', 'Price']
        for tr in outer_ratings_trs:
            o_tds_text = [td.text for td in tr.find_all('td')[1:]]
            if len(o_tds_text) == len(tags__): <<<<<<<<<<<<<<<<<<<<<<<
                outer_ratings_info.append({tags__[i]: o_tds_text[i] for i in range(0, len(tags__))})

        return pd.DataFrame(outer_ratings_info)
```

**Comment by oscar0812** [comment]
Hello. When is this happening? What function are you calling and with which arguments?

**Comment by drampelt** [comment]
I'm getting an error when fetching a Quote, I'm guessing it's the same problem. Here's the code and stack trace:

```python
>>> q = Quote('AAPL')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../lib/python3.10/site-packages/pyfinviz/quote.py", line 130, in __init__
    self.outer_ratings_df = Quote.__get_outer_ratings_df__(self.soup)
  File "/.../lib/python3.10/site-packages/pyfinviz/quote.py", line 21, in __get_outer_ratings_df__
    outer_ratings_info.append({tags__[i]: o_tds_text[i] for i in range(0, len(tags__))})
  File "/.../lib/python3.10/site-packages/pyfinviz/quote.py", line 21, in <dictcomp>
    outer_ratings_info.append({tags__[i]: o_tds_text[i] for i in range(0, len(tags__))})
IndexError: list index out of range
```

**Comment by ivnle** [comment]
It is the same issue as @drampelt described.

**Comment by oscar0812** [comment]
Thank you for the stack trace @drampelt. Looking into it.

**Comment by oscar0812** [comment]
Issue is fixed. Please update to the latest version and confirm:
`pip install pyfinviz==0.10`
I will close this issue once I receive confirmation. Thanks!

**Comment by ivnle** [comment]
Confirmed that 0.10 fixes the issue.
